### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by bteixeira** [orzechowskid/i18next-react-postprocessor#28]
Since there are currently no official type definitions published, integrating `i18next-react-postprocessor` in an existing TS project is very difficult (either I have to add the types manually or disable the type system altogether)

It took me a long time but I finally arrived at this definition file which seems to work:
```
declare module 'i18next-react-postprocessor' {
    import {Module} from 'i18next'

    type Options = {
        keepUnknownVariables: boolean
        prefix: string
        suffix: string
    }

    declare class ReactPostprocessor implements Module {
        type: 'postProcessor'
        constructor (opts?: Options)
    }

    export default ReactPostprocessor
}
```

I'm adding this as an issue and not PR because the definitions might not be complete and they need review.
In any case, the definitions above may help any one in the same situation even if it is not integrated in the repository.

**Comment by orzechowskid** [comment]
thanks, I just published v3.1.0 which should include your Typescript definition file (with a small modification).
